export const games = {
  flashcardHiraganaCharacters: {
    name: "ひらがなフラッシュカード",
    englishName: "Hiragana Flashcards",
    description: "ひらがなをフラッシュカードで学びましょう。",
    englishDescription: "Learn Hiragana through flashcards.",
    url: "/flashcard-hiragana",
  },
  flashcardKatakanaCharacters: {
    name: "カタカナフラッシュカード",
    englishName: "Katakana Flashcards",
    description: "カタカナをフラッシュカードで学びましょう。",
    englishDescription: "Learn Katakana through flashcards.",
    url: "/flashcard-katakana",
  },
  flashcard: {
    name: "フラッシュカード",
    englishName: "Flashcard",
    description: "フラッシュカードで様々なレベルの漢字を学びましょう。",
    englishDescription: "Learn kanji at various levels using flashcards.",
    url: "/flashcard",
    levels: [
      { name: "JLPT N5", url: "/flashcard/jlpt-5" },
      { name: "JLPT N4", url: "/flashcard/jlpt-4" },
      { name: "JLPT N3", url: "/flashcard/jlpt-3" },
      { name: "JLPT N2", url: "/flashcard/jlpt-2" },
      { name: "JLPT N1", url: "/flashcard/jlpt-1" },
      // { name: "Jouyou", url: "/flashcard/jouyou" },
    ],
  },
  // kanjiQuiz: {
  //   name: "漢字クイズ",
  //   englishName: "Kanji Quiz",
  //   description: "漢字の読み方や意味をクイズ形式で学びましょう。",
  //   englishDescription: "Learn kanji readings and meanings through quizzes.",
  //   url: "/kanji-quiz",
  // },
  // kanjiWriting: {
  //   name: "漢字書き取り",
  //   englishName: "Kanji Writing",
  //   description: "漢字の書き取り練習をしましょう。",
  //   englishDescription: "Practice writing kanji.",
  //   url: "/kanji-writing",
  // },
  // kanjiMemory: {
  //   name: "漢字記憶",
  //   englishName: "Kanji Memory",
  //   description: "漢字の記憶力を試すゲームです。",
  //   englishDescription: "A game to test your kanji memory.",
  //   url: "/kanji-memory",
  // },
  // kanjiMatch: {
  //   name: "漢字マッチ",
  //   englishName: "Kanji Match",
  //   description: "漢字の意味や読み方をマッチングするゲームです。",
  //   englishDescription: "A game to match kanji meanings and readings.",
  //   url: "/kanji-match",
  // },
  // kanjiTyping: {
  //   name: "漢字タイピング",
  //   englishName: "Kanji Typing",
  //   description: "漢字のタイピング練習をしましょう。",
  //   englishDescription: "Practice typing kanji.",
  //   url: "/kanji-typing",
  // },
  // kanjiStrokeOrder: {
  //   name: "漢字の筆順",
  //   englishName: "Kanji Stroke Order",
  //   description: "漢字の正しい筆順を学びましょう。",
  //   englishDescription: "Learn the correct stroke order of kanji.",
  //   url: "/kanji-stroke-order",
  // },
  // kanjiReading: {
  //   name: "漢字の読み方",
  //   englishName: "Kanji Reading",
  //   description: "漢字の読み方を学びましょう。",
  //   englishDescription: "Learn how to read kanji.",
  //   url: "/kanji-reading",
  // },
  // kanjiWritingPractice: {
  //   name: "漢字書き取り練習",
  //   englishName: "Kanji Writing Practice",
  //   description: "漢字の書き取り練習をしましょう。",
  //   englishDescription: "Practice writing kanji.",
  //   url: "/kanji-writing-practice",
  // },
};
