export const partOfSpeech: Record<string, string> = {
  MA: "Martial Arts Term",
  X: "Rude Or X-Rated Term (Not Displayed In Educational Software)",
  abbr: "Abbreviation",
  "adj-i": "Adjective (Keiyoushi)",
  "adj-ix": "Adjective (Keiyoushi) - Yoi/Ii Class",
  "adj-na": "Adjectival Noun Or Quasi-Adjective (Keiyodoshi)",
  "adj-no": "Noun Which May Take The Genitive Case Particle “No”",
  "adj-pn": "Pre-Noun Adjectival (Rentaishi)",
  "adj-t": "“Taru” Adjective",
  "adj-f": "Noun Or Verb Acting Prenominally",
  "adj-kari": "“Kari” Adjective (Archaic)",
  "adj-ku": "“Ku” Adjective (Archaic)",
  "adj-shiku": "“Shiku” Adjective (Archaic)",
  "adj-nari": "Archaic/Formal Form Of Na-Adjective",
  adv: "Adverb (Fukushi)",
  "adv-to": "Adverb Taking The “To” Particle",
  arch: "Archaism",
  ateji: "Ateji (Phonetic) Reading",
  aux: "Auxiliary",
  "aux-v": "Auxiliary Verb",
  "aux-adj": "Auxiliary Adjective",
  Buddh: "Buddhist Term",
  chem: "Chemistry Term",
  chn: "Children’s Language",
  col: "Colloquialism",
  comp: "Computer Terminology",
  conj: "Conjunction",
  "cop-da": "Copula",
  ctr: "Counter",
  derog: "Derogatory",
  eK: "Exclusively Kanji",
  ek: "Exclusively Kana",
  exp: "Expressions (Phrases, Clauses, Etc.)",
  fam: "Familiar Language",
  fem: "Female Term Or Language",
  food: "Food Term",
  geom: "Geometry Term",
  gikun: "Gikun (Meaning As Reading) Or Jukujikun (Special Kanji Reading)",
  hon: "Honorific Or Respectful (Sonkeigo) Language",
  hum: "Humble (Kenjougo) Language",
  iK: "Word Containing Irregular Kanji Usage",
  id: "Idiomatic Expression",
  ik: "Word Containing Irregular Kana Usage",
  int: "Interjection (Kandoushi)",
  io: "Irregular Okurigana Usage",
  iv: "Irregular Verb",
  ling: "Linguistics Terminology",
  "m-sl": "Manga Slang",
  male: "Male Term Or Language",
  "male-sl": "Male Slang",
  math: "Mathematics",
  mil: "Military",
  n: "Noun (Common) (Futsuumeishi)",
  "n-adv": "Adverbial Noun (Fukushitekimeishi)",
  "n-suf": "Noun, Used As A Suffix",
  "n-pref": "Noun, Used As A Prefix",
  "n-t": "Noun (Temporal) (Jisoumeishi)",
  num: "Numeric",
  oK: "Word Containing Out-Dated Kanji",
  obs: "Obsolete Term",
  obsc: "Obscure Term",
  ok: "Out-Dated Or Obsolete Kana Usage",
  oik: "Old Or Irregular Kana Form",
  "on-mim": "Onomatopoeic Or Mimetic Word",
  pn: "Pronoun",
  poet: "Poetical Term",
  pol: "Polite (Teineigo) Language",
  pref: "Prefix",
  proverb: "Proverb",
  prt: "Particle",
  physics: "Physics Terminology",
  rare: "Rare",
  sens: "Sensitive",
  sl: "Slang",
  suf: "Suffix",
  uK: "Word Usually Written Using Kanji Alone",
  uk: "Word Usually Written Using Kana Alone",
  unc: "Unclassified",
  yoji: "Yojijukugo",
  v1: "Ichidan Verb",
  "v1-s": "Ichidan Verb – Kureru Special Class",
  "v2a-s": "Nidan Verb With ‘U’ Ending (Archaic)",
  "v2k-k": "Nidan Verb (Upper Class) With ‘Ku’ Ending (Archaic)",
  "v2g-k": "Nidan Verb (Upper Class) With ‘Gu’ Ending (Archaic)",
  "v2t-k": "Nidan Verb (Upper Class) With ‘Tsu’ Ending (Archaic)",
  "v2d-k": "Nidan Verb (Upper Class) With ‘Dzu’ Ending (Archaic)",
  "v2h-k": "Nidan Verb (Upper Class) With ‘Hu/Fu’ Ending (Archaic)",
  "v2b-k": "Nidan Verb (Upper Class) With ‘Bu’ Ending (Archaic)",
  "v2m-k": "Nidan Verb (Upper Class) With ‘Mu’ Ending (Archaic)",
  "v2y-k": "Nidan Verb (Upper Class) With ‘Yu’ Ending (Archaic)",
  "v2r-k": "Nidan Verb (Upper Class) With ‘Ru’ Ending (Archaic)",
  "v2k-s": "Nidan Verb (Lower Class) With ‘Ku’ Ending (Archaic)",
  "v2g-s": "Nidan Verb (Lower Class) With ‘Gu’ Ending (Archaic)",
  "v2s-s": "Nidan Verb (Lower Class) With ‘Su’ Ending (Archaic)",
  "v2z-s": "Nidan Verb (Lower Class) With ‘Zu’ Ending (Archaic)",
  "v2t-s": "Nidan Verb (Lower Class) With ‘Tsu’ Ending (Archaic)",
  "v2d-s": "Nidan Verb (Lower Class) With ‘Dzu’ Ending (Archaic)",
  "v2n-s": "Nidan Verb (Lower Class) With ‘Nu’ Ending (Archaic)",
  "v2h-s": "Nidan Verb (Lower Class) With ‘Hu/Fu’ Ending (Archaic)",
  "v2b-s": "Nidan Verb (Lower Class) With ‘Bu’ Ending (Archaic)",
  "v2m-s": "Nidan Verb (Lower Class) With ‘Mu’ Ending (Archaic)",
  "v2y-s": "Nidan Verb (Lower Class) With ‘Yu’ Ending (Archaic)",
  "v2r-s": "Nidan Verb (Lower Class) With ‘Ru’ Ending (Archaic)",
  "v2w-s":
    "Nidan Verb (Lower Class) With ‘U’ Ending And ‘We’ Conjugation (Archaic)",
  v4h: "Yodan Verb With ‘Hu/Fu’ Ending (Archaic)",
  v4k: "Yodan Verb With ‘Ku’ Ending (Archaic)",
  v4g: "Yodan Verb With ‘Gu’ Ending (Archaic)",
  v4r: "Yodan Verb With ‘Ru’ Ending (Archaic)",
  v4s: "Yodan Verb With ‘Su’ Ending (Archaic)",
  v4t: "Yodan Verb With ‘Tsu’ Ending (Archaic)",
  v4n: "Yodan Verb With ‘Nu’ Ending (Archaic)",
  v4b: "Yodan Verb With ‘Bu’ Ending (Archaic)",
  v4m: "Yodan Verb With ‘Mu’ Ending (Archaic)",
  v5aru: "Godan Verb – ‘-aru’ Special Class",
  v5b: "Godan Verb With ‘Bu’ Ending",
  v5g: "Godan Verb With ‘Gu’ Ending",
  v5k: "Godan Verb With ‘Ku’ Ending",
  "v5k-s": "Godan Verb – Iku/Yuku Special Class",
  v5m: "Godan Verb With ‘Mu’ Ending",
  v5n: "Godan Verb With ‘Nu’ Ending",
  v5r: "Godan Verb With ‘Ru’ Ending",
  "v5r-i": "Godan Verb With ‘Ru’ Ending (Irregular Verb)",
  v5s: "Godan Verb With ‘Su’ Ending",
  v5t: "Godan Verb With ‘Tsu’ Ending",
  v5u: "Godan Verb With ‘U’ Ending",
  "v5u-s": "Godan Verb With ‘U’ Ending (Special Class)",
  v5uru: "Godan Verb – Uru Old Class Verb (Old Form Of Eru)",
  vz: "Ichidan Verb – Zuru Verb (Alternative Form Of -Jiru Verbs)",
  vi: "Intransitive Verb",
  vk: "Kuru Verb – Special Class",
  vn: "Irregular Nu Verb",
  vr: "Irregular Ru Verb, Plain Form Ends With -Ri",
  vs: "Suru Verb (Noun Or Participle Which Takes The Aux. Verb Suru)",
  "vs-c": "Su Verb – Precursor To The Modern Suru",
  "vs-s": "Suru Verb – Special Class",
  "vs-i": "Suru Verb – Irregular",
  vt: "Transitive Verb",
  "v-unspec": "Verb, Unspecified",
  kyb: "Kyoto-Ben",
  osb: "Osaka-Ben",
  ksb: "Kansai-Ben",
  ktb: "Kantou-Ben",
  tsb: "Tosa-Ben",
  thb: "Touhoku-Ben",
  tsug: "Tsugaru-Ben",
  kyu: "Kyuushuu-Ben",
  rkb: "Ryuukyuu-Ben",
  nab: "Nagano-Ben",
  hob: "Hokkaido-Ben",
  archit: "Architecture Term",
  astron: "Astronomy Term",
  baseb: "Baseball Term",
  biol: "Biology Term",
  bot: "Botany Term",
  bus: "Business Term",
  econ: "Economics Term",
  engr: "Engineering Term",
  finc: "Finance Term",
  geol: "Geology Term",
  law: "Law Term",
  mahj: "Mahjong Term",
  med: "Medicine Term",
  music: "Music Term",
  Shinto: "Shinto Term",
  shogi: "Shogi Term",
  sports: "Sports Term",
  sumo: "Sumo Term",
  zool: "Zoology Term",
  joc: "Jocular, Humorous Term",
  anat: "Anatomical Term",
};
